#!/usr/bin/env python3
"""Gate which exported conversations are allowed into the repo.

Writes a default-deny .gitignore inside the conversation folder: everything is
ignored, and each conversation gets a commented-out "un-ignore" line. Delete the
leading "# " from a line to publish that conversation; put it back to withdraw
it. Your existing choices are preserved when the list is re-synced.

Each entry is annotated with the result of scan_convos.py, so the decision is
made with the findings in front of you.

Usage:
    python publish_convos.py                     # sync the list for ./llm_convos
    python publish_convos.py path/to/convos      # sync a different folder
    python publish_convos.py --check             # fail if anything unsafe is allowed
    python publish_convos.py --allow NAME.md     # publish one conversation
    python publish_convos.py --deny NAME.md      # withdraw one conversation
    python publish_convos.py --status            # show what is allowed
    python publish_convos.py --install-hook      # add a pre-commit backstop

Exit codes: 0 ok, 1 unsafe content is allowed, 2 error.
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from scan_convos import scan_file, scan_text, summarise, worst_severity

DEFAULT_DIR = "llm_convos"
ALLOW_RE = re.compile(r"^(?P<comment>#\s*)?!(?P<name>.+?)\s*$")

HEADER = """\
# ==========================================================================
#  Conversation exports — DEFAULT DENY
#
#  Nothing in this folder reaches the repo unless it is listed below with an
#  active "!" line. To PUBLISH a conversation, delete the leading "# " from
#  its "!" line. To WITHDRAW one, put the "# " back.
#
#  Status tags come from scripts/scan_convos.py:
#     [clean]   nothing found
#     [review]  personal information found — only you can judge it
#     [BLOCK]   credentials found — do not publish, rotate the key
#
#  This file is regenerated by scripts/publish_convos.py, which preserves
#  whatever you have chosen to publish. Re-run it after exporting again.
# ==========================================================================

# Ignore everything in this folder,
*
# except this file.
!.gitignore

# ---- conversations -------------------------------------------------------
"""


BOOTSTRAP = """\
# Conversation exports — DEFAULT DENY.
#
# Nothing in this folder reaches the repo until it is explicitly allowed.
# Run scripts/publish_convos.py to list the conversations, see what each one
# contains, and choose which to publish.

*
!.gitignore
"""


def ensure_gitignore(convo_dir):
    """Put a deny-all .gitignore in place the moment the folder exists.

    Without this there is a window between exporting and running the gate in
    which a `git add -A` would commit every conversation.
    """
    gitignore = Path(convo_dir) / ".gitignore"
    if gitignore.exists():
        return False
    gitignore.parent.mkdir(parents=True, exist_ok=True)
    gitignore.write_text(BOOTSTRAP, encoding="utf-8")
    return True


def git_tracked(convo_dir):
    """Filenames git already tracks in this folder.

    Tracked files ignore .gitignore entirely, so they are published whatever
    the allow-list says. This is the gap that makes an ignore-only gate unsafe.
    """
    try:
        out = subprocess.run(
            ["git", "ls-files", "--", "."],
            capture_output=True, text=True, check=True, cwd=convo_dir,
        ).stdout
    except (subprocess.CalledProcessError, FileNotFoundError, NotADirectoryError):
        return set()
    return {Path(line).name for line in out.splitlines()
            if line.strip() and line.strip() != ".gitignore"}


def _git(convo_dir, *args):
    """Run a git command inside the conversation folder, or return None."""
    try:
        return subprocess.run(
            ["git", *args], capture_output=True, text=True, check=True, cwd=convo_dir,
        ).stdout
    except (subprocess.CalledProcessError, FileNotFoundError, NotADirectoryError):
        return None


def git_staged_files(convo_dir):
    """Filenames in this folder that are in git's index, i.e. about to commit."""
    out = _git(convo_dir, "ls-files", "--cached", "--", ".")
    if out is None:
        return []
    return [Path(l).name for l in out.splitlines()
            if l.strip() and Path(l).name != ".gitignore"]


def git_staged_content(convo_dir, name):
    """The staged bytes of a file, which may differ from the working tree."""
    return _git(convo_dir, "show", f":./{name}")


def git_untrack(convo_dir, name):
    """Stop tracking a file without deleting it from disk."""
    try:
        subprocess.run(
            ["git", "rm", "--cached", "--quiet", "--", name],
            capture_output=True, text=True, check=True, cwd=convo_dir,
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


TAG_RE = re.compile(r"^#\s*---\s*\[(?P<tag>\w+)\]\s+(?P<name>.+?)\s*$")

# Ordering of the risk tags. A rise means the file is no longer the thing you
# approved, so an existing publish choice should not carry over silently.
RISK = {"unscanned": 0, "clean": 0, "review": 1, "BLOCK": 2}


def read_entries(gitignore_path):
    """Return {filename: (is_allowed, recorded_tag_or_None)} from a gitignore."""
    entries = {}
    tags = {}
    if not gitignore_path.is_file():
        return entries
    for line in gitignore_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        tag_match = TAG_RE.match(line)
        if tag_match:
            tags[tag_match.group("name")] = tag_match.group("tag")
            continue
        match = ALLOW_RE.match(line)
        if not match:
            continue
        name = match.group("name").strip()
        if name == ".gitignore":
            continue
        entries[name] = (match.group("comment") is None, tags.get(name))
    return entries


def read_choices(gitignore_path):
    """Return {filename: is_allowed} from an existing gitignore."""
    return {n: allowed for n, (allowed, _) in read_entries(gitignore_path).items()}


def describe(findings, limit=4):
    """Short human lines describing what was found."""
    ordered = sorted(
        findings,
        key=lambda f: (-("NOTE", "REVIEW", "BLOCK").index(f.rule.severity), f.line_no),
    )
    lines = [
        f"#     {f.rule.severity} line {f.line_no}: {f.rule.description}"
        for f in ordered[:limit]
    ]
    if len(ordered) > limit:
        lines.append(f"#     ... and {len(ordered) - limit} more")
    return lines


def tag_for(findings):
    worst = worst_severity(findings)
    return {None: "clean", "NOTE": "clean", "REVIEW": "review", "BLOCK": "BLOCK"}[worst]


def sync(convo_dir, quiet=False, scan=True):
    """Regenerate the gitignore, preserving publish choices that still hold.

    A choice carries over unless the conversation's risk has risen since it was
    made -- new personal information, or a credential. In that case the entry is
    re-commented and reported, so re-publishing is always a deliberate act.
    """
    gitignore = convo_dir / ".gitignore"
    previous = read_entries(gitignore)
    files = sorted(convo_dir.glob("*.md"))

    body, report, withdrawn = [], [], []
    for path in files:
        was_allowed, prev_tag = previous.get(path.name, (False, None))

        if scan:
            findings = scan_file(path)
            tag = tag_for(findings)
        else:
            # Keep whatever was recorded rather than discarding what we know
            findings, tag = [], prev_tag or "unscanned"

        allowed = was_allowed
        if was_allowed and scan:
            risen = (RISK[tag] > RISK[prev_tag]) if prev_tag else (tag == "BLOCK")
            if risen:
                allowed = False
                withdrawn.append((path.name, prev_tag or "unknown", tag, findings))

        body.append(f"# --- [{tag}] {path.name}")
        body.extend(describe([f for f in findings if f.rule.severity != "NOTE"]))
        body.append(f"!{path.name}" if allowed else f"# !{path.name}")
        body.append("")
        report.append((path.name, tag, allowed, findings))

    gitignore.write_text(HEADER + "\n".join(body) + "\n", encoding="utf-8")

    if not quiet:
        _report_sync(convo_dir, gitignore, files, report, previous, withdrawn)
    return report


def _report_sync(convo_dir, gitignore, files, report, previous, withdrawn):
    new = [n for n, *_ in report if n not in previous]
    print(f"Synced {gitignore}")
    print(f"  {len(files)} conversation(s), {sum(1 for r in report if r[2])} published")
    if new:
        print(f"  {len(new)} new (added ignored by default):")
        for n in new[:10]:
            print(f"      {n}")

    if withdrawn:
        print(f"\n\033[33m⚠ UNPUBLISHED {len(withdrawn)} conversation(s)\033[0m — "
              "new findings since you approved them\n")
        for name, before, after, findings in withdrawn:
            print(f"    {name}")
            print(f"      \033[33m[{before}] → [{after}]\033[0m")
            for f in findings:
                if f.rule.severity == "BLOCK":
                    print(f"      BLOCK line {f.line_no}: {f.rule.description}")
            if after == "review":
                for f in findings:
                    if f.rule.severity == "REVIEW":
                        print(f"      REVIEW line {f.line_no}: {f.rule.description}")
                        break
        print("\n  They have been re-commented in the list. Re-publish once happy:")
        print(f"      python3 publish_convos.py --allow {withdrawn[0][0][:34]}")

    tracked = git_tracked(convo_dir)
    stale = sorted(tracked - {n for n, _, on, _ in report if on})
    if stale:
        print(f"\n  \033[33mWarning:\033[0m {len(stale)} file(s) are tracked by "
              "git despite not being published.")
        print("  .gitignore does not apply to tracked files — untrack them with:")
        for n in stale[:10]:
            print(f"      python3 publish_convos.py --deny {n}")


def check(convo_dir, staged=False):
    """Fail if anything published carries BLOCK findings.

    With staged=True, scan the content git is about to commit rather than the
    working tree. The two can differ -- `git add` then edit, or `git add -p` --
    and it is the staged version that ends up in history.
    """
    if staged:
        return _check_staged(convo_dir)

    gitignore = convo_dir / ".gitignore"
    if not gitignore.is_file():
        print(f"No {gitignore} — run publish_convos.py first.", file=sys.stderr)
        return 2

    choices = read_choices(gitignore)
    tracked = git_tracked(convo_dir)
    # Anything git tracks is published regardless of the allow-list
    allowed = sorted({n for n, on in choices.items() if on} | tracked)
    if not allowed:
        print("Nothing is published. Safe.")
        return 0

    stale = sorted(tracked - {n for n, on in choices.items() if on})
    if stale:
        print(f"\033[33mWarning:\033[0m {len(stale)} file(s) tracked by git but not "
              "marked for publication —\n  .gitignore cannot hide a tracked file:")
        for n in stale:
            print(f"    {n}")
        print()

    problems = []
    for name in allowed:
        path = convo_dir / name
        if not path.is_file():
            print(f"  warning: published entry has no file: {name}", file=sys.stderr)
            continue
        findings = scan_file(path)
        counts = summarise(findings)
        if counts["BLOCK"]:
            problems.append((name, findings))
            print(f"\n\033[31m✗ {name}\033[0m — {counts['BLOCK']} BLOCK finding(s)")
            for f in findings:
                if f.rule.severity == "BLOCK":
                    print(f"    line {f.line_no}: {f.rule.description}: {f.display}")
        else:
            tally = "  ".join(f"{k}:{v}" for k, v in counts.items() if v) or "clean"
            print(f"\033[32m✓\033[0m {name} — {tally}")

    if problems:
        print(f"\n{len(problems)} published conversation(s) contain credentials.",
              file=sys.stderr)
        print("Withdraw them and rotate the exposed keys:", file=sys.stderr)
        for name, _ in problems:
            print(f"    python3 publish_convos.py --deny {name}", file=sys.stderr)
        return 1

    print(f"\n{len(allowed)} published conversation(s), no credentials found.")
    return 0


def _check_staged(convo_dir):
    """Scan exactly what a commit would record."""
    names = git_staged_files(convo_dir)
    if not names:
        print("No conversations staged. Safe.")
        return 0

    problems = []
    for name in sorted(names):
        content = git_staged_content(convo_dir, name)
        if content is None:
            continue
        findings = scan_text(content, name)
        counts = summarise(findings)
        if counts["BLOCK"]:
            problems.append(name)
            print(f"\n\033[31m✗ {name}\033[0m — {counts['BLOCK']} BLOCK finding(s) "
                  "in the staged content")
            for f in findings:
                if f.rule.severity == "BLOCK":
                    print(f"    line {f.line_no}: {f.rule.description}: {f.display}")
        else:
            tally = "  ".join(f"{k}:{v}" for k, v in counts.items() if v) or "clean"
            print(f"\033[32m✓\033[0m {name} — {tally}")

    if problems:
        print(f"\n{len(problems)} staged conversation(s) contain credentials.",
              file=sys.stderr)
        print("Unstage them and rotate the exposed keys:", file=sys.stderr)
        for name in problems:
            print(f"    git restore --staged {name}", file=sys.stderr)
        return 1

    print(f"\n{len(names)} staged conversation(s), no credentials found.")
    return 0


def set_choice(convo_dir, name, allowed):
    """Publish or withdraw one conversation."""
    path = convo_dir / name
    if not path.is_file():
        matches = [p for p in convo_dir.glob("*.md") if name.lower() in p.name.lower()]
        if len(matches) != 1:
            print(f"No single match for {name!r} in {convo_dir}", file=sys.stderr)
            for m in matches[:10]:
                print(f"  candidate: {m.name}", file=sys.stderr)
            return 2
        path = matches[0]

    if allowed:
        findings = scan_file(path)
        if summarise(findings)["BLOCK"]:
            print(f"Refusing to publish {path.name} — it contains credentials:",
                  file=sys.stderr)
            for f in findings:
                if f.rule.severity == "BLOCK":
                    print(f"    line {f.line_no}: {f.rule.description}", file=sys.stderr)
            return 1

    gitignore = convo_dir / ".gitignore"
    choices = read_choices(gitignore)
    choices[path.name] = allowed
    # Re-sync with the updated choice baked in
    if gitignore.is_file():
        text = gitignore.read_text(encoding="utf-8")
        pattern = re.compile(rf"^#?\s*!{re.escape(path.name)}\s*$", re.MULTILINE)
        replacement = f"!{path.name}" if allowed else f"# !{path.name}"
        text, n = pattern.subn(replacement, text)
        if n:
            gitignore.write_text(text, encoding="utf-8")
            print(f"{'Published' if allowed else 'Withdrew'} {path.name}")
            if not allowed and path.name in git_tracked(convo_dir):
                if git_untrack(convo_dir, path.name):
                    print(f"  untracked from git (file kept on disk)")
                    print("  note: it remains in earlier commits — rewrite history "
                          "or rotate any exposed key")
                else:
                    print(f"  \033[33mstill tracked by git\033[0m — run: "
                          f"git rm --cached {path.name}", file=sys.stderr)
            return 0
    sync(convo_dir, quiet=True)
    return set_choice(convo_dir, path.name, allowed) if not gitignore.is_file() else 0


def status(convo_dir):
    choices = read_choices(convo_dir / ".gitignore")
    if not choices:
        print("No entries — run publish_convos.py to build the list.")
        return 2
    for name, allowed in sorted(choices.items()):
        mark = "\033[32mpublished\033[0m" if allowed else "ignored  "
        print(f"  {mark}  {name}")
    print(f"\n{sum(choices.values())} of {len(choices)} published")
    return 0


HOOK = """#!/bin/sh
# Refuse a commit whose staged content contains credentials.
root=$(git rev-parse --show-toplevel)
python3 "$root/scripts/publish_convos.py" --check --staged --dir "$root/{dirname}" || {{
    echo "pre-commit: blocked by conversation scan (git commit --no-verify overrides)" >&2
    exit 1
}}
"""


def install_hook(convo_dir):
    try:
        root = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=True, cwd=convo_dir,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("Not inside a git repository — nothing to install.", file=sys.stderr)
        return 2

    # Honour core.hooksPath: with husky or pre-commit installed, git never
    # looks in .git/hooks and a hook written there would silently never run.
    custom = (_git(convo_dir, "config", "--get", "core.hooksPath") or "").strip()
    hooks_dir = Path(root) / custom if custom else Path(root) / ".git" / "hooks"
    if custom:
        print(f"Note: core.hooksPath is set, installing into {hooks_dir}")
    hook_path = hooks_dir / "pre-commit"
    if hook_path.exists():
        print(f"A pre-commit hook already exists at {hook_path}.", file=sys.stderr)
        print("Add this line to it yourself:", file=sys.stderr)
        print(f"  python3 scripts/publish_convos.py --check --staged "
              f"--dir {convo_dir.name}", file=sys.stderr)
        return 2

    hook_path.parent.mkdir(parents=True, exist_ok=True)
    rel = convo_dir.resolve().relative_to(Path(root).resolve())
    hook_path.write_text(HOOK.format(dirname=rel), encoding="utf-8")
    hook_path.chmod(0o755)
    print(f"Installed {hook_path}")
    return 0


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Gate which exported conversations are allowed into the repo.",
    )
    parser.add_argument("dir_positional", nargs="?", default=None,
                        help=f"Conversation folder (default: ./{DEFAULT_DIR})")
    parser.add_argument("--dir", dest="dir_flag", default=None,
                        help="Conversation folder (same as the positional form)")
    parser.add_argument("--check", action="store_true",
                        help="Fail if a published conversation contains credentials")
    parser.add_argument("--staged", action="store_true",
                        help="With --check, scan what git is about to commit "
                             "rather than the working tree")
    parser.add_argument("--status", action="store_true", help="Show what is published")
    parser.add_argument("--allow", metavar="NAME", help="Publish one conversation")
    parser.add_argument("--deny", metavar="NAME", help="Withdraw one conversation")
    parser.add_argument("--install-hook", action="store_true",
                        help="Install a pre-commit hook that runs --check")
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    convo_dir = Path(args.dir_flag or args.dir_positional or DEFAULT_DIR).expanduser()

    if not convo_dir.is_dir():
        print(f"No conversation folder at {convo_dir}", file=sys.stderr)
        print("Run export_all_convos.py first.", file=sys.stderr)
        return 2

    if args.install_hook:
        return install_hook(convo_dir)
    if args.status:
        return status(convo_dir)
    if args.check:
        return check(convo_dir, staged=args.staged)
    if args.allow:
        return set_choice(convo_dir, args.allow, True)
    if args.deny:
        return set_choice(convo_dir, args.deny, False)

    sync(convo_dir)
    print(f"\nEdit {convo_dir / '.gitignore'} to choose what to publish,")
    print(f"or run: python3 {Path(__file__).name} --allow <name>")
    return 0


if __name__ == "__main__":
    sys.exit(main())
